forward:
  - id: Rule 1
    source: -368123010
    destination:
      - -584675883
    options:
      disable_notification: true
      from_background: true
    send_copy: false
    remove_caption: true
    stake_currency: "USDT"
